### ISSUE TITLE
Discover Devices does not see 7.1.X devices

### ISSUE THREAD

**Issue by radionerd** [IOTReboot/TasUI#1]
A device with Tasmota version 6.5.0 is discovered
but Devices with Tasmota version 7.1.0, 7.1.1 or 7.1.2 are not discovered

**Comment by radionerd** [comment]
Using the work around 'SetOption73 1' (Set HTTP Cross-Origin Resource Sharing) at the Tasmota console achieves successful discovery for Tasmota versions 7.1.0, 7.1.1 and 7.1.2. Thanks for a very useful project.

**Comment by shantur** [comment]
@radionerd : TasUI is dependent on CORS to work. Its now mentioned in here http://tasui.shantur.com/#/findDevices

Thanks for using it.
