### ISSUE TITLE
some devices not being discovered

### ISSUE THREAD

**Issue by jpadie** [IOTReboot/TasUI#15]
i have a few active tasmota devices in my network that are not being discovered by the javascript client.  accessible by MQTT, web and by Alexa discovery.  But the JS client never finds it.  Configured as a W-DEXI module. 

Is there a setting needed to ensure it is discoverable?

**Comment by shantur** [comment]
@jpadie : Check a couple of things

1. What version of Tasmota are they running
2. If you are setting correct IP Address range

**Comment by jpadie** [comment]
@shantur
thanks - definitely using the correct range.  all my devices except one are in the same subnet and they are all appearing.  to note that the (currently) missing device is on a known IP address in that subnet and is accessible via the web interface.

all current devices are on 8.1.0.  

i will reflash and zero out the stored settings and see whether it's just a glitch.

**Comment by shantur** [comment]
@jpadie : Can you try to send `CORS http://tasui.shantur.com` for some device and try discovery

**Comment by jpadie** [comment]
@shantur 

i reflashed the device and it is now appearing.  

thanks for the engagement.
