### ISSUE TITLE
TasUI won't start

### ISSUE THREAD

**Issue by rdhuff** [IOTReboot/TasUI#16]
Message: [FATAL tini (7)] exec docker-entrypoint.sh failed: Exec format error

I'm running a pretty standard default Hass.io install on RaspberryPi 4.

**Comment by mrvnklm** [comment]
Same here, seems to be an issue with build for ARM CPUs

**Comment by mrvnklm** [comment]
Okay I figured it out, you got to change `effelle/tasui-exp` to `iotreboot/tasui` in config.json

**Comment by effelle** [comment]
Yep. But the official have issue with https I still need to resolve.
