### ISSUE TITLE
Incorrect spelling 'Pusletime'

### ISSUE THREAD

**Issue by fourwallz** [IOTReboot/TasUI#19]
Should read "Pulsetime" not Pusletime

**Comment by fourwallz** [comment]
![F6F3E765-BCFE-4C7C-B710-FCAA6E64D26D](https://user-images.githubusercontent.com/55113595/83948712-dfa08b00-a7d3-11ea-9e43-e09338aac979.png)

**Comment by shantur** [comment]
Thanks. Fixed
