### ISSUE TITLE
Discovery IP Range does not default to local Subnet

### ISSUE THREAD

**Issue by robclark56** [IOTReboot/TasUI#23]
LOVE the product by the way.

When first firing up TasUI, the Start/End IP address do not match the local subnet.

e.g in my case:

- Local subnet: 10.1.1.0/24

- TasUI start/end IP: 192.168.10.1 - 192.168.10.254

Is that fixable?

**Comment by shantur** [comment]
Not fixable. Browser cannot detect the IP range of your network
