### ISSUE TITLE
Not discovering devices with serial

### ISSUE THREAD

**Issue by LucReynders** [IOTReboot/TasUI#4]
Tasui looks great.  Discovered all my devices except 2 .
 Both use the serial connection on gpio1/3  and read the values of a PZEM power monitoring device.
Is this related to the fact that serial is used ? Both upgraded to tasmota 8.1.0 and option73 on.

**Comment by effelle** [comment]
If you are using Tasmota 8 then you must enable `CORS` under wifi settings adding 
`http://tasui.shantur.com` as domain.

**Comment by LucReynders** [comment]
Thanks. I was not aware of this change for version 8.0.
Applied this to one of the devices,  works fine.
